name: PHP CodeSniffer

on:
  push:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Kies de PHP-versie die je wilt gebruiken

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs

