name: Controleer puntkomma's achter zinnen

on:
  push:
    branches:
      - main

jobs:
  check-semicolons:
    runs-on: ubuntu-latest

    steps:
    - name: Controleer code uit
      uses: actions/checkout@v2

    - name: Controleer puntkomma's
      run: |
        if grep -RnE '^[^}]+[^;]$' . ; then
          echo "Fout: Geen puntkomma achter zin gevonden."
          exit 1
        fi
