name: Deploy PHP Page to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: Deploy to GitHub Pages
        run: |
          # Stel de uitvoermap in waarin de PHP-bestanden zich bevinden
          output_dir="public"

          # Maak een map om de uitvoerbestanden in op te slaan
          mkdir -p $output_dir

          # Kopieer PHP-bestanden naar de uitvoermap
          cp -R test $output_dir

          # Configuratie voor GitHub Pages
          git config --global user.email "D287404@edu.curio.nl"
          git config --global user.name "Jamiroschroevers"
          mv -f $output_dir/* ./
          git add .
          git commit -m "Deployed PHP page"
          git push origin gh-pages  # Als de branche voor GitHub Pages anders is, pas dit dan aan
