name: PHP Semicolon Check
on: [push]

jobs:
  php-semicolon-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check PHP files for missing semicolons
        run: |
          find . -name "*.php" -exec sh -c '
            for file do
              if ! grep -q ";$" "$file"; then
                echo "Missing semicolon at the end of a line in $file"
                exit 1
              fi
            done
          ' _ {} +
